package com.sensetime.greendaodemo.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sensetime.greendaodemo.db.entity.FaceInfo;

import com.sensetime.greendaodemo.db.dao.FaceInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig faceInfoDaoConfig;

    private final FaceInfoDao faceInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        faceInfoDaoConfig = daoConfigMap.get(FaceInfoDao.class).clone();
        faceInfoDaoConfig.initIdentityScope(type);

        faceInfoDao = new FaceInfoDao(faceInfoDaoConfig, this);

        registerDao(FaceInfo.class, faceInfoDao);
    }
    
    public void clear() {
        faceInfoDaoConfig.clearIdentityScope();
    }

    public FaceInfoDao getFaceInfoDao() {
        return faceInfoDao;
    }

}
